const data = [
    {
        "id": 1,
        "courseName": "The Complete 2023 Web Development Bootcamp",
        "image": "https://img-c.udemycdn.com/course/240x135/1565838_e54e_18.jpg",
        "creator": "Dr. Angela Yu",
        "category": "development",
        "subcategory": "webdev",
        "rating": 4.7,
        "hrs": 63,
        "lectures": 380,
        "price": 5000,
        "offerPrice": 3100,
        "point1": "Build 16 web development projects for your portfolio, ready to apply for junior developer jobs.",
        "point2": "Learn the latest technologies, including Javascript, React, Node and even Web3 development.",
        "point3": "After the course you will be able to build ANY website you want."
    },
    {
        "id": 2,
        "courseName": "The Web Developer Bootcamp 2023",
        "image": "https://img-c.udemycdn.com/course/240x135/625204_436a_3.jpg",
        "creator": "Colt Steele",
        "category": "development",
        "subcategory": "webdev",
        "rating": 4.6,
        "hrs": 52,
        "lectures": 300,
        "price": 5230,
        "offerPrice": 2100,
        "point1": "The ins and outs of HTML5, CSS3, and Modern JavaScript for 2021",
        "point2": "Make REAL web applications using cutting-edge technologies",
        "point3": "Create responsive, accessible, and beautiful layouts"
    },
    {
        "id": 3,
        "courseName": "Angular - The Complete Guide",
        "image": "https://img-c.udemycdn.com/course/240x135/756150_c033_2.jpg",
        "creator": "Maximillan",
        "category": "development",
        "subcategory": "webdev",
        "rating": 4.7,
        "hrs": 36,
        "lectures": 35,
        "price": 4500,
        "offerPrice": 2300,
        "point1": "Develop modern, complex, responsive and scalable web applications with Angular",
        "point2": "Fully understand the architecture behind an Angular application and how to use it",
        "point3": "Use the gained, deep understanding of the Angular fundamentals to quickly establish yourself as a frontend developer"
    },
    {
        "id": 4,
        "courseName": "The Complete JavaScript Course 2024: From Zero to Expert!",
        "image": "https://img-c.udemycdn.com/course/240x135/851712_fc61_6.jpg",
        "creator": "Jonas",
        "category": "development",
        "subcategory": "webdev",
        "rating": 4,
        "hrs": 36,
        "lectures": 23,
        "price": 5800,
        "offerPrice": 3100,
        "point1": "Become an advanced, confident, and modern JavaScript developer from scratch",
        "point2": "Build 6 beautiful real-world projects for your portfolio (not boring toy apps)",
        "point3": "Become job-ready by understanding how JavaScript really works behind the scenes"
    },
    {
        "id": 5,
        "courseName": "Build Responsive Real-World Websites with HTML and CSS",
        "image": "https://img-c.udemycdn.com/course/240x135/437398_46c3_10.jpg",
        "creator": "Jonas",
        "category": "development",
        "subcategory": "webdev",
        "rating": 3.6,
        "hrs": 46,
        "lectures": 200,
        "price": 3500,
        "offerPrice": 1000,
        "point1": "Become a modern and confident HTML and CSS developer, no prior knowledge needed!",
        "point2": "Design and build a stunning real-world project for your portfolio from scratch",
        "point3": "Modern, semantic and accessible HTML5"
    },
    {
        "id": 6,
        "courseName": "Modern React with Redux [2023 Update]",
        "image": "https://img-c.udemycdn.com/course/240x135/705264_caa9_13.jpg",
        "creator": "Stephen Grider",
        "category": "development",
        "subcategory": "webdev",
        "rating": 3,
        "hrs": 46,
        "lectures": 200,
        "price": 3500,
        "offerPrice": 1000,
        "point1": "Create dynamic web apps using the latest in web technology",
        "point2": "Acquire the programming skills needed to obtain a software engineering job",
        "point3": "Practice your skills with many large projects, exercises, and quizzes"
    },
    {
        "id": 7,
        "courseName": "The Complete Web Developer Course 3.0",
        "image": "https://img-c.udemycdn.com/course/240x135/764164_de03_5.jpg",
        "creator": "Rob Percival",
        "category": "development",
        "subcategory": "webdev",
        "rating": 4.5,
        "hrs": 13,
        "lectures": 20,
        "price": 1500,
        "offerPrice": 999,
        "point1": "Build websites and webapps",
        "point2": "Build HTML-based mobile apps",
        "point3": "Get a job as a junior web developer"
    },
    {
        "id": 8,
        "courseName": "The Complete Web Developer in 2023: Zero to Mastery",
        "image": "https://img-c.udemycdn.com/course/240x135/1430746_2f43_10.jpg",
        "creator": "Andrie Neagoie",
        "category": "development",
        "subcategory": "webdev",
        "rating": 4.6,
        "hrs": 12,
        "lectures": 5,
        "price": 4500,
        "offerPrice": 2600,
        "point1": "Skills that will allow you to apply for jobs like: Web Developer, Software Developer, Front End Developer, Javascript Developer, and Full Stack Developer",
        "point2": "Learn modern technologies that are ACTUALLY being used behind tech companies in 2023",
        "point3": "Build 10+ real world Web Development projects you can show off"
    },
    {
        "id": 9,
        "courseName": "Machine Learning A-Z™: AI, Python & R + ChatGPT Bonus [2023]",
        "image": "https://img-c.udemycdn.com/course/240x135/950390_270f_3.jpg",
        "creator": "Kirill Eremenko",
        "category": "development",
        "subcategory": "datasci",
        "rating": 2.5,
        "hrs": 12,
        "lectures": 100,
        "price": 5600,
        "offerPrice": 2100,
        "point1": "Master Machine Learning on Python & R",
        "point2": "Have a great intuition of many Machine Learning models",
        "point3": "Make accurate predictions"
    },
    {
        "id": 10,
        "courseName": "Python for Data Science and Machine Learning Bootcamp",
        "image": "https://img-c.udemycdn.com/course/240x135/903744_8eb2.jpg",
        "creator": "Jose Portilla",
        "category": "development",
        "subcategory": "datasci",
        "rating": 4.6,
        "hrs": 13,
        "lectures": 25,
        "price": 5600,
        "offerPrice": 1500,
        "point1": "Use Python for Data Science and Machine Learning",
        "point2": "Use Spark for Big Data Analysis",
        "point3": "Implement Machine Learning Algorithms"
    },
    {
        "id": 11,
        "courseName": "The Data Science Course: Complete Data Science Bootcamp 2023",
        "image": "https://img-c.udemycdn.com/course/240x135/1754098_e0df_3.jpg",
        "creator": "365 Careers",
        "category": "development",
        "subcategory": "datasci",
        "rating": 2.6,
        "hrs": 46,
        "lectures": 200,
        "price": 3500,
        "offerPrice": 1000,
        "point1": "Impress interviewers by showing an understanding of the data science field",
        "point2": "The course provides the entire toolbox you need to become a data scientist",
        "point3": "Fill up your resume with in demand data science skills: Statistical analysis, Python programming with NumPy, pandas, matplotlib, and Seaborn, Advanced statistical analysis, Tableau, Machine Learning with stats models and scikit-learn, Deep learning with TensorFlow"
    },
    {
        "id": 12,
        "courseName": "R Programming A-Z™: R For Data Science With Real Exercises!",
        "image": "https://img-c.udemycdn.com/course/240x135/765242_2578_6.jpg",
        "creator": "Kirill Ereneko",
        "category": "development",
        "subcategory": "datasci",
        "rating": 4.6,
        "hrs": 46,
        "lectures": 200,
        "price": 3500,
        "offerPrice": 3000,
        "point1": "Learn to program in R at a good level",
        "point2": "Learn how to use R Studio",
        "point3": "Learn the core principles of programming"
    },
    {
        "id": 13,
        "courseName": "Deep Learning A-Z™ 2023: Neural Networks, AI & ChatGPT Bonus",
        "image": "https://img-c.udemycdn.com/course/240x135/1778502_f4b9_12.jpg",
        "creator": "Kirill Eremenko",
        "category": "development",
        "subcategory": "mobiledev",
        "rating": 4.6,
        "hrs": 46,
        "lectures": 150,
        "price": 4500,
        "offerPrice": 3300,
        "point1": "Understand the intuition behind Artificial Neural Networks",
        "point2": "Apply Artificial Neural Networks in practice",
        "point3": "Understand the intuition behind Convolutional Neural Networks"
    },
    {
        "id": 14,
        "courseName": "Statistics for Data Science and Business Analysis",
        "image": "https://img-c.udemycdn.com/course/240x135/1708340_7108_5.jpg",
        "creator": "365 Careers",
        "category": "development",
        "subcategory": "mobiledev",
        "rating": 4.6,
        "hrs": 13,
        "lectures": 20,
        "price": 4500,
        "offerPrice": 1000,
        "point1": "Understand the fundamentals of statistics",
        "point2": "Learn how to work with different types of data",
        "point3": "How to plot different types of data"
    },
    {
        "id": 15,
        "courseName": "Artificial Intelligence A-Z 2023: Build 5 AI (incl. ChatGPT)",
        "image": "https://img-c.udemycdn.com/course/240x135/2259120_305f_6.jpg",
        "creator": "Hadelin de pontevas",
        "category": "development",
        "subcategory": "mobiledev",
        "rating": 3.6,
        "hrs": 46,
        "lectures": 200,
        "price": 3500,
        "offerPrice": 1000,
        "point1": "Build an AI",
        "point2": "Understand the theory behind Artificial Intelligence",
        "point3": "Make a virtual Self Driving Car"
    },
    {
        "id": 16,
        "courseName": "Data Science A-Z™: Hands-On Exercises & ChatGPT Bonus [2023]",
        "image": "https://img-c.udemycdn.com/course/240x135/959700_8bd2_12.jpg",
        "creator": "Kirill Eremenko",
        "category": "development",
        "subcategory": "mobiledev",
        "rating": 3.6,
        "hrs": 46,
        "lectures": 42,
        "price": 5600,
        "offerPrice": 3200,
        "point1": "Perform Data Mining in Tableau",
        "point2": "Create Basic Tableau Visualisations",
        "point3": "Successfully perform all steps in a complex Data Science project"
    },
    {
        "id": 17,
        "courseName": "The Complete Python Bootcamp From Zero to Hero in Python",
        "image": "https://img-c.udemycdn.com/course/240x135/567828_67d0.jpg",
        "creator": "jose Portilla",
        "category": "development",
        "subcategory": "programlang",
        "rating": 4.6,
        "hrs": 10,
        "lectures": 23,
        "price": 4800,
        "offerPrice": 356,
        "point1": "You will learn how to leverage the power of Python to solve tasks.",
        "point2": "You will build games and programs that use Python libraries.",
        "point3": "You will be able to use Python for your own work problems or personal projects."
    },
    {
        "id": 18,
        "courseName": "100 Days of Code: The Complete Python Pro Bootcamp for 2023",
        "image": "https://img-c.udemycdn.com/course/240x135/2776760_f176_10.jpg",
        "creator": "Dr. Angela Yu",
        "category": "development",
        "subcategory": "programlang",
        "rating": 4.7,
        "hrs": 45,
        "lectures": 23,
        "price": 9899,
        "offerPrice": 999,
        "point1": "You will master the Python programming language by building 100 unique projects over 100 days.",
        "point2": "You will learn automation, game, app and web development, data science and machine learning all using Python.",
        "point3": "You will be able to program in Python professionally"
    },
    {
        "id": 19,
        "courseName": "React - The Complete Guide 2023 (incl. React Router & Redux)",
        "image": "https://img-c.udemycdn.com/course/240x135/1362070_b9a1_2.jpg",
        "creator": "Maximillan",
        "category": "development",
        "subcategory": "programlang",
        "rating": 4.6,
        "hrs": 12,
        "lectures": 8,
        "price": 4500,
        "offerPrice": 1000,
        "point1": "Learn React from the ground up and finish the course as an advanced React developer",
        "point2": "Build multiple high-quality demo apps, including a fullstack app built with NextJS",
        "point3": "Join more than 750,000 students in this course & more than 2,500,000 students I taught across all my courses"
    },
    {
        "id": 20,
        "courseName": "Java 17 Masterclass: Start Coding in 2023",
        "image": "https://img-c.udemycdn.com/course/240x135/533682_c10c_4.jpg",
        "creator": "Tim Buchalka",
        "category": "development",
        "subcategory": "programlang",
        "rating": 4.6,
        "hrs": 8,
        "lectures": 2,
        "price": 1200,
        "offerPrice": 999,
        "point1": "Learn the core Java skills needed to apply for Java developer positions in just 14 hours.",
        "point2": "Be able to sit for and pass the Oracle Java Certificate exam if you choose.",
        "point3": "Be able to demonstrate your understanding of Java to future employers."
    },
    {
        "id": 21,
        "courseName": "Automate the Boring Stuff with Python Programming",
        "image": "https://img-c.udemycdn.com/course/240x135/543600_64d1_4.jpg",
        "creator": "AI Sweigart",
        "category": "development",
        "subcategory": "programlang",
        "rating": 4.6,
        "hrs": 13,
        "lectures": 10,
        "price": 4500,
        "offerPrice": 2320,
        "point1": "Automate tasks on their computer by writing simple Python programs.",
        "point2": "Write programs that can do text pattern recognition with 'regular expressions'.",
        "point3": "Programmatically generate and update Excel spreadsheets."
    },
    {
        "id": 22,
        "courseName": "An Entire MBA in 1 Course:Award Winning Business School Prof",
        "image": "https://img-c.udemycdn.com/course/240x135/637930_9a22_19.jpg",
        "creator": "chris Haroun",
        "category": "business",
        "subcategory": "entrepreneurship",
        "rating": 4.5,
        "hrs": 2,
        "lectures": 4,
        "price": 5600,
        "offerPrice": 3399,
        "point1": "Over 450,000 students in 195 countries!",
        "point2": "Superb reviews!",
        "point3": "Free 384 page book version of this course included!"
    },
    {
        "id": 23,
        "courseName": "MBA in a Box: Business Lessons from a CEO",
        "image": "https://img-c.udemycdn.com/course/240x135/1269254_1df3_8.jpg",
        "creator": "365 Careers",
        "category": "business",
        "subcategory": "entrepreneurship",
        "rating": 4.6,
        "hrs": 12,
        "lectures": 20,
        "price": 8999,
        "offerPrice": 2999,
        "point1": "Receive an 'MBA in a Box' certificate of completion",
        "point2": "Acquire the same business acumen as MBA graduates",
        "point3": "How to start a company from scratch"
    },
    {
        "id": 24,
        "courseName": "Blogging Masterclass: How To Build A Successful Blog In 2023",
        "image": "https://img-c.udemycdn.com/course/240x135/1058614_b13f_3.jpg",
        "creator": "Brad Merril",
        "category": "business",
        "subcategory": "entrepreneurship",
        "rating": 3,
        "hrs": 23,
        "lectures": 10,
        "price": 7856,
        "offerPrice": 1230,
        "point1": "Build a successful blog from scratch, or take your existing blog to the next level",
        "point2": "Develop the mindset of a successful blogger",
        "point3": "Discover a blogging niche that is both profitable and interesting"
    },
    {
        "id": 25,
        "courseName": "The Complete Business Plan Course (Includes 50 Templates)",
        "image": "https://img-c.udemycdn.com/course/240x135/1787702_b6d4_3.jpg",
        "creator": "Chris Haroun",
        "category": "business",
        "subcategory": "entrepreneurship",
        "rating": 4.6,
        "hrs": 12,
        "lectures": 23,
        "price": 8999,
        "offerPrice": 5900,
        "point1": "Create an incredible business plan from scratch.",
        "point2": "Understand how to take any type of business to the next level (meaning a start-up or an established business).",
        "point3": "Create a perfect Executive Summary write-up part of the Business Plan."
    },
    {
        "id": 26,
        "courseName": "Master Strategic Thinking and Problem Solving Skills",
        "image": "https://img-c.udemycdn.com/course/240x135/986604_b4cc_3.jpg",
        "creator": "Warren Chalklen",
        "category": "business",
        "subcategory": "entrepreneurship",
        "rating": 4,
        "hrs": 3,
        "lectures": 1,
        "price": 1299,
        "offerPrice": 999,
        "point1": "Learn how to make better decisions and plan strategically",
        "point2": "Use the models to resolve conflicts and deliver great feedback",
        "point3": "Conduct a product analysis"
    },
    {
        "id": 27,
        "courseName": "Intro to Entrepreneurship: Get started as an Entrepreneur",
        "image": "https://img-c.udemycdn.com/course/240x135/662354_4ff7_7.jpg",
        "creator": "Evan Kimbrell",
        "category": "business",
        "subcategory": "entrepreneurship",
        "rating": 4.7,
        "hrs": 20,
        "lectures": 200,
        "price": 5899,
        "offerPrice": 3999,
        "point1": "Understand and apply all the core concepts of Entrepreneurship",
        "point2": "Tell the difference between the realities of Entrepreneurship & the common myths",
        "point3": "Assess their own personality through the lens of Entrepreneurship & know how to find partners that have what they are lacking"
    },
    {
        "id": 28,
        "courseName": "Communication Fundamentals: How To Communicate Better",
        "image": "https://img-c.udemycdn.com/course/240x135/1355610_375a_5.jpg",
        "creator": "Life Progression Project",
        "category": "business",
        "subcategory": "communication",
        "rating": 5,
        "hrs": 2,
        "lectures": 1,
        "price": 5000,
        "offerPrice": 2500,
        "point1": "Improve your email writing skills in simple steps",
        "point2": "Communicate with different personalities",
        "point3": "Communicate with different personalities"
    },
    {
        "id": 29,
        "courseName": "Write Better Emails: Tactics for Smarter Team Communication",
        "image": "https://img-c.udemycdn.com/course/240x135/946654_dbfb_3.jpg",
        "creator": "Hassan Osman",
        "category": "business",
        "subcategory": "communication",
        "rating": 4.6,
        "hrs": 23,
        "lectures": 15,
        "price": 4999,
        "offerPrice": 3500,
        "point1": "Learn proper email etiquette and business writing techniques that get you results",
        "point2": "Learn proper email etiquette and business writing techniques that get you results",
        "point3": "Avoid common errors in email messages that confuse people"
    },
    {
        "id": 30,
        "courseName": "Email Etiquette: Write More Effective Emails At Work",
        "image": "https://img-c.udemycdn.com/course/240x135/552372_1adb.jpg",
        "creator": "Clare Lynch",
        "category": "business",
        "subcategory": "communication",
        "rating": 3.6,
        "hrs": 46,
        "lectures": 200,
        "price": 3500,
        "offerPrice": 1000,
        "point1": "Write punchier, more powerful emails every time",
        "point2": "Contribute to a positive workplace culture through email",
        "point3": "Never write an embarrassing or ineffective email ever again"
    },
    {
        "id": 31,
        "courseName": "Cross-Cultural Communication: How To Flex Your Style",
        "image": "https://img-c.udemycdn.com/course/240x135/1366348_9ff2_5.jpg",
        "creator": "Life Progression Project",
        "category": "business",
        "subcategory": "communication",
        "rating": 3.6,
        "hrs": 46,
        "lectures": 200,
        "price": 3500,
        "offerPrice": 2000,
        "point1": "Learn how to communicate Cross-Culturally"
    },
    {
        "id": 32,
        "courseName": "Active Listening: You Can Be a Great Listener",
        "image": "https://img-c.udemycdn.com/course/240x135/3438904_aad7.jpg",
        "creator": "Lauren Powers",
        "category": "business",
        "subcategory": "communication",
        "rating": 4.6,
        "hrs": 4,
        "lectures": 12,
        "price": 5600,
        "offerPrice": 2000,
        "point1": "Identify & overcome common habits of reacting (that are not really listening!)",
        "point2": "Shift attention from your own thoughts over to the speaker (for that’s what the speaker cares about!)",
        "point3": "Develop, & practice, observing the speaker’s words and energy (as they are communicating so much!)"
    },
    {
        "id": 33,
        "courseName": "Leadership: Practical Leadership Skills",
        "image": "https://img-c.udemycdn.com/course/240x135/613808_3c1c_6.jpg",
        "creator": "Chris Croff",
        "category": "business",
        "subcategory": "management",
        "rating": 4.6,
        "hrs": 46,
        "lectures": 200,
        "price": 3500,
        "offerPrice": 1000,
        "point1": "Become a Master in Leadership",
        "point2": "Be a better boss, and run a highly effective team",
        "point3": "Delegate effectively to empower their team"
    },
    {
        "id": 34,
        "courseName": "Become a Product Manager | Learn the Skills & Get the Job",
        "image": "https://img-c.udemycdn.com/course/240x135/673654_d677_7.jpg",
        "creator": "Cole Mercer",
        "category": "business",
        "subcategory": "management",
        "rating": 3,
        "hrs": 45,
        "lectures": 200,
        "price": 3500,
        "offerPrice": 2500,
        "point1": "Understand the varying role of a Product Manager through different types and sizes of companies",
        "point2": "Decide which type of Product Manager best fits one's goals and personality",
        "point3": "Understand the Product Lifecycle and how it applies to every product"
    },
    {
        "id": 35,
        "courseName": "The Customer: How to Understand Their Needs (BITE SIZE)",
        "image": "https://img-c.udemycdn.com/course/240x135/640936_32e9_2.jpg",
        "creator": "Learoy Tonight",
        "category": "business",
        "subcategory": "management",
        "rating": 2,
        "hrs": 1,
        "lectures": 1,
        "price": 3500,
        "offerPrice": 1000,
        "point1": "Recognise how internal service impacts external service",
        "point2": "Define internal and external customers",
        "point3": "Determine factors that create customer value"
    },
    {
        "id": 36,
        "courseName": "Consulting Approach to Problem Solving",
        "image": "https://img-c.udemycdn.com/course/240x135/1037646_193c_22.jpg",
        "creator": "Piotr Gawlicki",
        "category": "business",
        "subcategory": "management",
        "rating": 2.6,
        "hrs": 23,
        "lectures": 45,
        "price": 7899,
        "offerPrice": 2666,
        "point1": "You will understand and appreciate the problem solving technique used by the top consulting firms like McKinsey, BCG, Bain and Strategy&",
        "point2": "At the same time you will get acquainted with how business and consulting projects ought to be structured",
        "point3": "You will master the basic knowledge on hypothesis-based problem solving that will let you proceed to more advanced courses on solving business problems"
    },
    {
        "id": 37,
        "courseName": "Managing Change: Learn to thrive through change.",
        "image": "https://img-c.udemycdn.com/course/240x135/166240_d837_4.jpg",
        "creator": "Caroline Samne",
        "category": "business",
        "subcategory": "management",
        "rating": 4.7,
        "hrs": 10,
        "lectures": 10,
        "price": 5666,
        "offerPrice": 1200,
        "point1": "Understand and use the 3 phases of a transition to thrive during a time of dramatic change",
        "point2": "Understand the difference between a change process and a transition process",
        "point3": "Create an action plan to manage the transition"
    },
    {
        "id": 38,
        "courseName": "Sales Training: Practical Sales Techniques",
        "image": "https://img-c.udemycdn.com/course/240x135/563478_2c35.jpg",
        "creator": "Chris Croft",
        "category": "business",
        "subcategory": "sales",
        "rating": 4,
        "hrs": 4,
        "lectures": 2,
        "price": 5600,
        "offerPrice": 1200,
        "point1": "Enjoy selling by befriending customers",
        "point2": "Close deals with confidence",
        "point3": "Be organised and efficient"
    },
    {
        "id": 39,
        "courseName": "Customer Service Mastery: Delight Every Customer",
        "image": "https://img-c.udemycdn.com/course/240x135/1919728_cf04_6.jpg",
        "creator": "Chris Croft",
        "category": "business",
        "subcategory": "sales",
        "rating": 4.6,
        "hrs": 23,
        "lectures": 45,
        "price": 4899,
        "offerPrice": 3899,
        "point1": "Be flooded with ideas on how to delight customers",
        "point2": "Stand out from competitors with unique customer experiences",
        "point3": "Create customers who are loyal for life and sing your praises to friends and family"
    },
    {
        "id": 40,
        "courseName": "Business Development & B2B Sales for Startups- Sales Valley",
        "image": "https://img-c.udemycdn.com/course/240x135/1449746_ca17_2.jpg",
        "creator": "Patrick Dang",
        "category": "business",
        "subcategory": "sales",
        "rating": 3.6,
        "hrs": 46,
        "lectures": 200,
        "price": 3500,
        "offerPrice": 1000,
        "point1": "Students will learn the PROVEN Sales Valley Methodology to build business relationships and generate sales",
        "point2": "How to sell and generate meetings remotely and be productive while working from home",
        "point3": "All the different types of business development deal structures you can use to grow your business"
    },
    {
        "id": 41,
        "courseName": "LinkedIn Marketing, Lead Generation & B2B Sales for LinkedIn",
        "image": "https://img-c.udemycdn.com/course/240x135/1794901_d8ac_2.jpg",
        "creator": "Patrick Dang",
        "category": "business",
        "subcategory": "sales",
        "rating": 3.6,
        "hrs": 46,
        "lectures": 200,
        "price": 3500,
        "offerPrice": 1000,
        "point1": "How generate a massive amount of leads using cutting edge sales & marketing LinkedIn lead generation strategies",
        "point2": "How to optimize your LinkedIn Profile to get 10x more visibility and generate leads",
        "point3": "How to convert LinkedIn leads and conversations into REAL meetings via phone or in-person"
    },
    {
        "id": 42,
        "courseName": "Customer Success Manager: Fundamentals to your CSM career",
        "image": "https://img-c.udemycdn.com/course/240x135/703316_a5ff_5.jpg",
        "creator": "Gustavo Escobar",
        "category": "business",
        "subcategory": "sales",
        "rating": 4.6,
        "hrs": 3,
        "lectures": 2,
        "price": 3500,
        "offerPrice": 1200,
        "point1": "Have a better understanding of what your job as Customer Success Manager will be like",
        "point2": "Understand the fundamental principles of Customer Success. Which will be the foundation for your career as a CSM",
        "point3": "Be more prepared for a Customer Success Manager job interview (we will not cover interview skills, but you will know more about customer success)"
    }
];

module.exports = data;